export const QUERY_KEYS = {
  DASHBOARD_REPORT: 'dashboard-report',
  MONTHLY_TOTALS:   'monthly-totals',
  EXPENSE_BY_CATEGORY: 'expense-by-category',
  ACCOUNT_BALANCES: 'account-balances',
  RECENT_MOVEMENTS: 'recent-movements',
  BUDGET_PROGRESS:  'budget-progress',
  ACCOUNTS:         'accounts',
  CURRENCIES:       'currencies',
  JOURNAL_ENTRIES:  'journal-entries',
  BUDGETS:          'budgets',
  MERCHANTS:        'merchants',
  TAGS:             'tags',
  SCHEDULED:        'scheduled',
  GOALS:            'goals',
}